export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';

export const TOGGLE_TASK_COMPLETETION = 'TOGGLE_TASK_COMPLETETION';
export const FILTER_TASK_COMPLETETION = 'FILTER_TASK_COMPLETETION';